name: Sync
on:
  workflow_dispatch:
  
jobs:
  sync-branches:
    strategy:
      matrix:
        #branch: [mutator, Weapons, User-Interface, SpellSystem, Room-Layouts, PickupSystem, Minimap, Initial_Asset_Adding, Grid-System, CreateEnemy, Boss]
        branch: [User-Interface]
        
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Open pull request
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: development
          target_branch: ${{ matrix.branch }}
          title: Sync Pull Request
